services:
  - type: web
    name: pneumonia-detection-app
    env: python
    pythonVersion: "3.10.12"
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
